### ISSUE TITLE
Ios problem

### ISSUE THREAD

**Issue by antoniohof** [ccrma/chunity#7]
DllNotFoundException: Unable to load DLL 'AudioPluginChuck'

How to add the DLL to ios build?

Thanks,

Antonio

**Comment by gewang** [comment]
For Chunity iOS, there is no Chunity DLL to load. By design, Chunity iOS compiles the source code as part of the Unity-generated XCode project. The steps include:

<img width="640" alt="Screen Shot 2024-05-04 at 10 26 45 PM" src="https://github.com/ccrma/chunity/assets/669967/46e8e63f-5c7d-4ede-880d-3aae5afc2e1d">

1) open Unity -> File -> Build Settings
2) select "iOS" under "Platform"
3) click "Switch Platform"
4) (optional: make sure at least one scene is selected)
5) click "Build"

This should generate a new XCode project that by default compiles the Chunity Boilerplate project for iOS. You should be able to see the Chunity as well as ChucK core C++ source files as part of this project.

We hope this helps. cc @eitomurakami
